name: dw-lib

services:
  clickhouse:
    image: clickhouse/clickhouse-server:25.3.2.39-alpine
    environment:
      - CLICKHOUSE_USER=default
      - CLICKHOUSE_PASSWORD=default
      - CLICKHOUSE_DB=default
      - CLICKHOUSE_DEFAULT_ACCESS_MANAGEMENT=1
      - TZ=UTC
    ports:
      - 18123:8123
    healthcheck:
      test: wget --no-verbose --spider http://0.0.0.0:8123/ping || exit 1
      interval: 1s
      timeout: 1s
      retries: 10
    deploy:
      restart_policy:
        condition: on-failure

  postgres:
    image: postgres:17.4-alpine3.21
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=test
      - TZ=UTC
    ports:
      - 15432:5432
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -d $${POSTGRES_DB} -U $${POSTGRES_USER}"]
      interval: 1s
      timeout: 1s
      retries: 10
    deploy:
      restart_policy:
        condition: on-failure

  app:
    image: dw-lib-app:latest
    build: .
    environment:
      - TZ=UTC
    working_dir: /app
    volumes:
      - ./pyproject.toml:/app/pyproject.toml:ro
      - ./README.md:/app/README.md:ro
      - ./uv.lock:/app/uv.lock:ro
      - ./src:/app/src:ro
      - ./tests:/app/tests:ro
      - ./vendor/wait-for-it/wait-for-it.sh:/wait-for-it.sh:ro
    depends_on:
      - clickhouse
      - postgres
    stop_grace_period: 0s
    command: /wait-for-it.sh clickhouse:8123 -- /wait-for-it.sh postgres:5432 -- /bin/bash
    stdin_open: true
    tty: true
