[tools]
python = "3.13"
ripgrep = "latest"
trivy = "latest"
uv = "latest"
zizmor = "latest"

[settings]
lockfile = true
minimum_release_age = "7d"
python.uv_venv_auto = "create|source"

[hooks.enter]
run = """
mise install --quiet
uv sync --all-extras --all-groups --quiet
if [ -d .git ]; then pre-commit install --overwrite > /dev/null 2>&1; fi
"""
