[project]
name = "dw-lib"
version = "1.0.4"
description = "Tools for working with Postgres, ClickHouse, and DuckDB."
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "clickhouse-connect>=0.9.2",
    "clickhouse-sqlalchemy",
    "dbt-clickhouse",
    "dbt-core>=1.9.4,<1.10", # Pinned because of dbt-clickhouse
    "duckdb>=1.4.1",
    "duckdb-engine>=0.17.0",
    "httpx>=0.28.1",
    "jinja2>=3.1.6",
    "livereload>=2.7.1",
    "polyfactory>=2.22.2",
    "psutil>=7.1.0",
    "psycopg2-binary>=2.9.11",
    "pydantic>=2.12.1",
    "pydantic-settings>=2.11.0",
    "pydash>=8.0.5",
    "pyyaml>=6.0.3",
    "rich>=14.2.0",
    "sqlalchemy>=2.0.44",
    "sqlglot>=27.27.0",
    "sqlmodel>=0.0.27",
    "sqlparse>=0.5.3",
    "typer>=0.19.2",
]

[dependency-groups]
dev = [
    "pytest>=8.4.2",
    "pytest-docker>=3.2.3",
]

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[tool.isort]
force_alphabetical_sort = true
line_length = 100
profile = "black"
py_version = 313

[tool.ruff]
line-length = 100
target-version = "py313"

[tool.ruff.lint]
ignore = ["D100", "D101", "D102", "D103", "D104", "D107", "D205"]

[tool.pytest.ini_options]
addopts = "--no-header --tb=no"
filterwarnings = [
    "ignore::DeprecationWarning:dbt_common.invocation", # https://github.com/dbt-labs/dbt-core/issues/9791
    "ignore::DeprecationWarning:dbt.cli.options"        # https://github.com/dbt-labs/dbt-core/issues/12038
]

[tool.uv.sources]
clickhouse-sqlalchemy = { git = "https://github.com/netbek/clickhouse-sqlalchemy.git", rev = "datetime-uuid" }
dbt-clickhouse = { git = "https://github.com/netbek/dbt-clickhouse.git", rev = "v1.9.4-batch" }
