[project]
name = "dw-lib"
version = "1.24.3"
description = "Tools for working with Postgres, ClickHouse, and DuckDB."
readme = "README.md"
requires-python = "==3.13.*"

# sqlglot pinned for compatibility with dagster-dbt https://github.com/dagster-io/dagster/blob/1.12.19/python_modules/libraries/dagster-dbt/pyproject.toml#L33
dependencies = [
    "boto3>=1.41.1",
    "clickhouse-connect>=0.10.0",
    "clickhouse-sqlalchemy",
    "duckdb>=1.4.2",
    "duckdb-engine>=0.17.0",
    "httpx>=0.28.1",
    "jinja2>=3.1.6",
    "packaging>=26.0",
    "psutil>=7.1.3",
    "psycopg2-binary>=2.9.11",
    "pydantic>=2.12.4",
    "pydash>=8.0.5",
    "ruamel-yaml>=0.19.1",
    "sqlalchemy>=2.0.44",
    "sqlglot>=28.0.0,<30.1.0",
    "sqlmodel>=0.0.27",
    "sqlparse>=0.5.3",
]

[project.optional-dependencies]
dagster = [
    "dagster>=1.12.19",
    "dagster-dbt>=0.28.19",
]
# dbt-core pinned for compatibility with dbt-clickhouse https://github.com/netbek/dbt-clickhouse/blob/v1.10.0-batch/pyproject.toml#L26
dbt = [
    "dbt-clickhouse",
    "dbt-core>=1.10.0,<1.11",
    "livereload>=2.7.1",
    "opentelemetry-sdk>=1.39.1",
    "polyfactory>=3.0.0",
    "pydantic>=2.12.4",
    "pydash>=8.0.5",
    "ruamel-yaml>=0.19.1",
]
loader = [
    "boto3>=1.41.1",
    "chdb>=3.7.2",
    "jinja2>=3.1.6",
    "psycopg2-binary>=2.9.11",
    "pydantic>=2.12.4",
    "rich>=14.2.0",
]
peerdb = [
    "clickhouse-connect>=0.10.0",
    "clickhouse-sqlalchemy",
    "httpx>=0.28.1",
    "psycopg2-binary>=2.9.11",
    "pydantic>=2.12.4",
    "pydash>=8.0.5",
    "rich>=14.2.0",
    "ruamel-yaml>=0.19.1",
    "sqlalchemy>=2.0.44",
    "sqlglot>=28.0.0",
    "sqlmodel>=0.0.27",
]

[dependency-groups]
dev = [
    "pre-commit>=4.5.1",
    "pyright>=1.1.408",
    "pytest>=9.0.2",
    "pytest-docker>=3.2.5",
    "ruff>=0.15.0",
]

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[tool.isort]
force_alphabetical_sort = true
line_length = 100
profile = "black"
py_version = 313

[tool.ruff]
line-length = 100
target-version = "py313"
extend-exclude = ["./vendor"]

[tool.ruff.lint]
ignore = ["D100", "D101", "D102", "D103", "D104", "D107", "D205"]

[tool.pyright]
include = ["src", "tests"]
pythonVersion = "3.13"
typeCheckingMode = "basic"
reportPrivateImportUsage = "none"

[tool.pytest]
addopts = ["-x", "--no-header", "--container-scope=module"]
filterwarnings = [
    "ignore::DeprecationWarning:dbt_common.invocation", # https://github.com/dbt-labs/dbt-core/issues/9791
    "ignore::DeprecationWarning:dbt.cli.options"        # https://github.com/dbt-labs/dbt-core/issues/12038
]
markers = ["docker_skip_wait_until_responsive"]

[tool.uv.sources]
clickhouse-sqlalchemy = { git = "https://github.com/netbek/clickhouse-sqlalchemy.git", rev = "datetime-uuid" }
dbt-clickhouse = { git = "https://github.com/netbek/dbt-clickhouse.git", rev = "v1.10.0-batch" }
