class EmptyConfigException(Exception): ...


class PeerNotFoundException(Exception): ...


class PeerExistsException(Exception): ...


class MirrorNotFoundException(Exception): ...


class MirrorExistsException(Exception): ...


class TableNotFoundException(Exception): ...
