class EmptyConfigException(Exception): ...


class PeerNotFoundException(Exception): ...


class PeerExistsException(Exception): ...


class MirrorNotFoundException(Exception): ...


class MirrorExistsException(Exception): ...


class DatabaseExistsException(Exception): ...


class SchemaExistsException(Exception): ...


class TableExistsException(Exception): ...


class TableNotFoundException(Exception): ...


class UserExistsException(Exception): ...


class PublicationExistsException(Exception): ...
