[project]
name = "cli"
version = "0.1.0"
description = "CLI example"
readme = "README.md"
requires-python = "==3.13.*"
dependencies = [
    "dbt-clickhouse",
    "dbt-core>=1.10.0,<1.11", # Pinned because of dbt-clickhouse
    "example-cli",
]

[tool.uv.sources]
dbt-clickhouse = { git = "https://github.com/netbek/dbt-clickhouse.git", rev = "v1.9.8-batch" }
example-cli = { path = "./packages/example_cli", editable = true }
