name: CI

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: docker/setup-buildx-action@v3

      - uses: docker/build-push-action@v6
        with:
          tags: dw-lib:latest

      - run: |
          docker compose up -d
          docker compose exec app /wait-for-it.sh clickhouse:8123 -- /wait-for-it.sh postgres:5432 -- /wait-for-it.sh minio:9000 -- pytest
          docker compose down
