name: CI

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: docker/setup-buildx-action@v3

      - uses: docker/build-push-action@v6
        with:
          tags: dw-lib:latest

      - run: |
          docker compose up -d
          docker compose exec app pytest --ignore tests/adapters/test_clickhouse.py
          docker compose down
